modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL = "https://github.com/PhantomWing/RusticPancakes/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/PhantomWing/RusticPancakes"
logoFile= "../logo.png"
logoBlur=false
credits=""
authors="${mod_authors}"
description='''${mod_description}'''
## Catalogue mod compatibility
itemIcon = "rusticpancakes:chocolate_pancakes"
configBackground = "minecraft:textures/block/bricks.png"

[[dependencies.${mod_id}]] #optional
modId="forge" #mandatory
mandatory=true
versionRange="${forge_version_range}" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"